<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4MKSC1R" failures="1" tests="14" name="PetTest" time="28.111" errors="0" timestamp="2024-08-07T12:30:46 PKT">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="3.793"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.188">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testGetUserByName(UserTests2.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests2" name="testUpdateUser" time="2.417"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.19"/>
  <testcase classname="api.test.UserTests" name="testPostUser" time="3.52"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.228"/>
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="2.347"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.183"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.162"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.278"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="2.115"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.131"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.119"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.165"/>
</testsuite> <!-- PetTest -->
